### ISSUE TITLE
Preferences does not render as expected in 2.0.0.alpha2

### ISSUE THREAD

**Issue by sudr** [archi-contribs/specialization-plugin#43]
The preference form is rendering blank:

![image](https://user-images.githubusercontent.com/113617/98694447-74895080-233f-11eb-95c3-93aeaf150a28.png)

My JVM is on Mac OS version 10.15.7:
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.3+7
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=AdoptOpenJDK
java.vendor.url=https://adoptopenjdk.net/
java.vendor.url.bug=https://github.com/AdoptOpenJDK/openjdk-build/issues
java.vendor.version=AdoptOpenJDK
java.version=11.0.3
java.version.date=2019-04-16
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=AdoptOpenJDK
java.vm.version=11.0.3+7

**Comment by herve91** [comment]
Hi,

The preference page renders well. there is no more to show on the preference page.

I close the case.

Best regards
Hervé

**Comment by sudr** [comment]
When I click on the help icon it takes me to help page with this screenshot of the preferences:

![image](https://user-images.githubusercontent.com/113617/98750066-04a0b780-238b-11eb-9b77-2d2d6fcffcdb.png)

I don't see the "bahavior" and "image folder" sections.

**Comment by herve91** [comment]
I apologies, the help section comes from the version 1 of the plugin and has not been updated when I started the version 2. Please note that even if I started this version 2 ages ago, it is still in alpha preview stage, not even in beta.

**Comment by sudr** [comment]
No worries. I was really only trying to figure out how to set the image folder. In version 1 I could do it via this preference page. I'm not seeing how to do the same in 2.0.0.alpha2. If there isn't a way to set the image folder could you let me know what the default folder location is where I should place my images.

**Comment by herve91** [comment]
When I started the version 1 of the plugin, I was thing about changing the icon of every individual Archimate elements, one by one.

Then, when I got my Archimate certification, I thought it would be better to implement the specialization of elements as described in the Archimate documentation. That's why I started the version 2 of the plugin.

When you select your model, you then have a "specialization" tab that allows to create specializations for each type of elements and assign some defaults to these specializations (properties, format, color, icon, label, ...)
![image](https://user-images.githubusercontent.com/9281982/98912747-ca3c3500-24c6-11eb-9f18-c24fb37e98fb.png)

Then, when you create an element, you can choose a specialization and Archi automatically change its representation (format, label and icon) and add properties.

Unfortunately, I'm stuck by the fact that icons cannot be added to a model if they are not referenced in a view so I needed to create the "SpecializationPluginCanvas" view to store the images. The dark side is that this view is then dealt as any other view by Archi (it is exported in HTML and PDF exports, it can be manually edited by user, etc ...) which is a big issue for my own plugin usage.

That's the reason why I personaly stick to the plugin version 1 and that the version 2 is still is alpha release.

In addition, Archi can now natively change the label of elements, view per view, so except for changing icons, my plugin is not really useful anymore.

Best regards
Hervé

**Comment by sudr** [comment]
Thanks for the detailed response. I was using the plugin to drop custom icons on different elements in my view. Sounds like I should move back to 1.x version. 

Appreciate your work on this plugin.

**Comment by herve91** [comment]
version 1 has not been updated for ages and may not work with Archi 4.7 either :(

Please let me know if I need to recompile it as well.
