### ISSUE TITLE
Inconsistency in plugin installation

### ISSUE THREAD

**Issue by evlibra** [archi-contribs/specialization-plugin#50]
The [wiki documentation ](https://github.com/archi-contribs/specialization-plugin/wiki/Installation-and-Configuration) refers to using *.jar, but the new versions (master branch) contains *.arhiplugin only (it's renaming to zip and unzipping does not work). Or that is better to not touch latest, and we shall keep using what is in [branch](https://github.com/archi-contribs/specialization-plugin/tree/version_1): 1.0.0.11 vs 1.0.0.12 ?

By the way, judging from the file-extension, are new versions assumed to be [installed ](https://www.archimatetool.com/plugins/#installing) from the Help->Manage Plugins?
-At the moment it is not recognized as a plugin from there.

**Comment by herve91** [comment]
I know my wiki is not up to date, I lack time to update it but the file can be imported into Archi using Help->Manage Plugins.

You say it is not recognised as a plugin here, have you got an error message ?

**Comment by evlibra** [comment]
yes, it is not recognized. 
![image](https://user-images.githubusercontent.com/48681198/103917797-044b4100-50dc-11eb-89f1-3df10439c6d2.png)

**Comment by herve91** [comment]
It works on my Archi.

How did you download the file ? Please try to download it again. It should be 1 847 186 bytes.

Should you prefer, archiplugin files are ZIP files, so you may unzip it and you'll find the JAR file inside. But the Help->Manage Plugins is easier, that's why I  now deliver the plugin under this format.

**Comment by evlibra** [comment]
You're right. Thanks! Initially I did download by clicking on file and clicking download (the same effect was from right-click save-as), the filesize was 101 Kb. 
![image](https://user-images.githubusercontent.com/48681198/103925707-f00c4180-50e5-11eb-95ca-273051c880c5.png)

Resolved by "Download Zip"
![image](https://user-images.githubusercontent.com/48681198/103925909-33ff4680-50e6-11eb-9443-608a99794e2f.png)

**Comment by evlibra** [comment]
By the way, is 2.0.0.alpha2 worth trying? what are the major changes release notes? org.archicontribs.specialization_2.0.0.alpha2.archiplugin

Thanks for the tis great plugin!

**Comment by herve91** [comment]
You may try the version 2 without any risk on your model. The difference is that the plugin v2 allows to create a kind of template for components (label, icon, color, ...) and then to apply this template to Archimate Concepts. I stopped developing it because I'm obliged to store the images in a dedicated view that is visible in the model and the reports ... which is very bad.

but I'm not sure it is worth it ...

The plugin version 1 stores the label in the objects properties which implies that, as the properties are linked to the Archimate concept, so the label is applied in ALL views.

New version of Archi implements a label functionality but stores its information in new attributes (that did not exist when I developed the plugin) that are linked to the graphical objects rather than the Archimate concepts. So the labels are different across views.

Please be informed that Archi devs are working to add the ability to natively change the icons as well.

So from my point of view, my plugin is already deprecated from a label replacement point of view and will be quickly deprecated as well from an icon replacement point of view. I do not know if they will implement the drill down part of the plugin.
