### ISSUE TITLE
Icon not being replaced on Mac. Refer issue 6

### ISSUE THREAD

**Issue by mike548141** [archi-contribs/specialization-plugin#9]
History is under this issue https://github.com/archi-contribs/specialization-plugin/issues/6, this continues the issue using v1.0 of the plugin

**Comment by herve91** [comment]
Hi Mike,

I failed to get a Mac to do some testing on my side, so the only thing I can suggest is that we do some testing on _your_ Mac toghther.

Could you please contact me on my email address : herve.jouin@gmail.com that we can organize a webex session from my work desktop.

**Comment by herve91** [comment]
@mike548141 

The previous version was using an internal Archi method that could acces image files in the "editor" plugin folder only. The new version uses its own method to draw the image and can access any folder if declared on the preference page.

But the image file should be readable to be shown in an Archi component. and as I do not have any Mac, I do not know if there is a security parameter somewhere that disallow this kind of access.

but As you've done, it is possible to copy the icons you need from Archi's folder to an external one.

**Comment by mike548141** [comment]
@herve91 I just deleted the Archi.app and downloaded v4.1.1 of Archi.  v1.0 of your plugin now works as expected so my guess is it was an Archi issue somehow.

**Comment by herve91** [comment]
Hi Mike,

I'm happy it works now, so I close this issue. On my side, I continue to search for a solution to do some testing on Mac in the future.

Best regards
Hervé

**Comment by rich-biker** [comment]
I hate to go over old ground, but I wonder if anyone else is still having this problem on a Mac? (Weird that it's exactly a year ago since I tried getting round this!) 

I've tried the latest v1.0.10 and I still have this problem. No label replacement. No icon replacement. If I go backward to 1.0.7, it's all fine, but obviously I'm missing out on some good stuff. 

Here's a log.
[SpecializationPlugin_19Dec2018.log](https://github.com/archi-contribs/specialization-plugin/files/2694744/SpecializationPlugin_19Dec2018.log)

Also - when I was on 1.0.9, it wasn't actually doing the upgrade to 1.0.10, telling me "I have the latest".  I found out about that looking at the log file and getting it from GitHub.

**Comment by rich-biker** [comment]
I tried that exact named file yesterday, and for me, it didn't work. Then I just renamed that file as "org.archicontribs.specialization_v1.0.7.jar". Feels like some sort of manifest naming issue.

And thanks for all the effort with us Mac types.

**Comment by jwWays** [comment]
Had the same issue renaming whatever version to "org.archicontribs.specialization_v1.0.7.jar" solved my issues of not rendering label.
This is a great feature. thx Herve...

**Comment by herve91** [comment]
I conducted some tests with Gilles this morning and it appears that the plugin works will with OpenJdk but does not work with Oracle JDK.

I need to find out why ...
